Comment added (repo, service, model, entity)
ljungberg84/video-data pull request #3
Opened 2019-11-26 14:12 UTC by Maksym-Gorbunov

2019-11-26 15:18 UTC, antbli requested changes

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  private String dateCreated;
Skall vara en Instant?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  private String user;
Skall vara en UserEntity? Med en OneToOne-relation?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  private String likedByUser;
Skall vara en kollektion av LikeEntity? Jag har lite svårt att förstå hur den entiteten kommer fungera dock. Kanske hade det varit bättre om vi hade en kollektion av UserEntity för liked och en annan för disliked? Vi kan ta upp detta i skolan..

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  private Instant joinDate;
Se kommentarer för entityn

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  }
Vill vi ha konverteringsmetoderna i model-lagret? Kanske bättre att lägga i en egen klass och kanske t.o.m göra den generisk så kan alla entities/models använda den?

Var finns konverteringen från model till entity?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  }
Behöver vi ha en egen metod för att konvertera en lista? Iterationen skulle kunna ske från stället där vi kallar på denna och istället kalla på metoden ovan som vi redan har. Alternativt att vi kallar på metoden ovan inifrån denna.

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  public ResponseEntity<CommentModel> createComment(@Valid @RequestBody CommentEntity commentBody) throws Exception {
Bör denna inte ta emot en CommentModel?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  @GetMapping("/all")
Vill vi ha "/all" som path?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +    //return ResponseEntity.status(HttpStatus.OK).body(commentModel);
Ta bort kommentar?

2019-11-26 15:18 UTC, antbli commented on src/main/java/se/complexjava/videostreamingapi/service/CommentService.java
> +  CommentModel updateComment(CommentEntity comment);
Skall man ej speca Exception-typ? Inga exceptions för delete och update?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +  @Autowired
Behövs @Autowired?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  private Instant joinDate;
Vad är joinDate?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    comment.setJoinDate(Instant.now());
Vad är joinDate? Borde inte detta vara dateCreated?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    }
Jag har dålig koll. Varför vill man använda Optional?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    // check if exist, exceptions???
Vi får bestämma hur vi skall ha det här.

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  public ResponseEntity<CommentModel> getComment(@Valid @RequestBody CommentEntity commentBody) throws Exception {
Skall vi inte ta emot en model här.
Vi plockar inte in commentId från pathen.

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +    CommentModel commentModel = commentService.updateComment(commentBody);
Skicka med commentId?

2019-11-26 15:18 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    repository.save(commentToUpdate);
Här bör vi väl skicka med commentId, hitta matchande objekt och sedan uppdatera det hittade objektet därefter?

2019-11-26 15:18 UTC, blixtr commented on src/main/resources/application.properties
> +spring.datasource.password=123
Dessa ändringar bör väl inte pushas upp till github då dom är specifika för dig lokalt?

2019-11-26 15:19 UTC, blixtr commented
Kan du byta namn på branchen så att man vet vilken task den tillhör?

2019-11-27 09:48 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +import java.time.Instant;
rfadfasf

2019-11-27 09:52 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  @NotEmpty(message = "date created can't be null or empty")
Ta bort annotation

2019-11-27 10:08 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/entity/CommentEntity.java
> +  private String likedByUser;
Vi kör LikeCommentEntity

2019-11-27 10:24 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  }
Kör bara entity -> model i dagsläget

2019-11-27 10:25 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  }
Lägg konvertering i basklass Model

2019-11-27 10:29 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/model/CommentModel.java
> +  }
Overloada metod.

2019-11-27 10:30 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  public ResponseEntity<CommentModel> createComment(@Valid @RequestBody CommentEntity commentBody) throws Exception {
Vi kör som det är i dagsläget

2019-11-27 10:31 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  @GetMapping("/all")
Ta bort path

2019-11-27 10:37 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/rest/CommentController.java
> +  public ResponseEntity<CommentModel> getComment(@Valid @RequestBody CommentEntity commentBody) throws Exception {
Skall vara PUT.

2019-11-27 10:46 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    comment.setJoinDate(Instant.now());
Ta bort

2019-11-27 10:52 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    List<CommentEntity> comments = (List<CommentEntity>) repository.findAll();
Lägg Iterable istället för List

2019-11-27 11:04 UTC, blixtr commented on src/main/java/se/complexjava/videostreamingapi/service/CommentServiceImpl.java
> +    repository.save(commentToUpdate);
Kontrollera om det fungerar

2019-11-27 11:10 UTC, blixtr commented on src/main/resources/application.properties
> +spring.datasource.password=123
Lägg ej med

2019-11-29 11:22 UTC, closed without merging